Comment pre push husky

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,6 +1,6 @@
-#!/bin/sh
-npm run build:dev
-if [ $? -ne 0 ]; then
-  echo "Build failed. Push aborted."
-  exit 1
-fi
+# #!/bin/sh
+# npm run build:dev
+# if [ $? -ne 0 ]; then
+#   echo "Build failed. Push aborted."
+#   exit 1
+# fi
